### ISSUE TITLE
Interactivity warning misplaced

### ISSUE THREAD

**Issue by droumis** [holoviz-dev/nbsite#286]
The interactivity_warning component from NotebookDirective is misplaced, I think because of the latest pydata_sphinx_theme 

![image](https://github.com/holoviz-dev/nbsite/assets/6613202/7a0d8930-9e8d-46ed-9f79-cea3bd4baa98)

It should be in the right corner and look like this:

![image](https://github.com/holoviz-dev/nbsite/assets/6613202/8af16187-a7bf-40e7-88c4-e09699b5fd38)

**Comment by maximlt** [comment]
It's fine on the latest version.

![image](https://github.com/user-attachments/assets/59157c53-0e6c-4ad9-9281-c36597b5c972)
