### ISSUE TITLE
Add GoatCounter

### ISSUE THREAD

**Issue by maximlt** [holoviz-dev/nbsite#294]
I set up Goatcounter for the HoloViz blog as an experiment, we decided it was good enough for our purposes and to implement it across all our sites.

![image](https://github.com/holoviz-dev/nbsite/assets/35924738/caaef001-4892-40ea-a0ee-85615c11ab63)

Implementation-wise, we can add support for it in nbsite directly (possibly upstreamed later to the pydata theme), basically copying what was recently done in the conda ecosystem https://github.com/conda-incubator/conda-sphinx-theme/pull/9. I have already implemented most of it.

There are a few issues to resolve/decisions to make before finishing the implementation and opening PRs on every project:

- Goatcounter doesn't really support tracking of multiple subdomains (e.g. panel.holoviz.org, lumen.holoviz.org) on the same dashboard; when multiple sites send data to Goatcounter the page views in the dashboard all seem to come from the same domain by default. There are two alternative ways to address that:

  1. creating multiple accounts, each dedicated to a subdomain (I checked it's possible to create multiple accounts with the same email)
  2. registering multiple sites on the same account, and injecting some JavaScript on each site to send the domain to Goatcounter is it's prefixed before each path (this is explained in the documentation)

  This is all described in more detail in [the documentation](https://www.goatcounter.com/help/domains). I think I have a small preference for option 2. It's worth noting that Goatcounter has an API from which we could fetch the data it collects to store it and display it the way we want in a Panel/Lumen app.

- Goatcounter will send page views even on the dev sites (e.g. ), this can be [prevented in javascript](https://www.goatcounter.com/help/skip-dev#skip-loading-staging-beta-sites-26), alternatively, we could not enable Goatcounter in Python in `conf.py`, depending on the environment built. Or we could just live with that (interestingly if we choose option 2. above we'll actually be able to check whether there isn't too much traffic on the dev sites).

---

Potential future use cases:
- Panel apps could send "page views" to Goatcounter, see [from app backends or other sources](https://www.goatcounter.com/help/backend)

**Comment by droumis** [comment]
> ii. registering multiple sites on the same account, and injecting some JavaScript on each site to send the domain to Goatcounter is prefixed before each path (this is explained in the documentation)

I'm in favor of this option as well. 

> Goatcounter will send page views even on the dev sites

I highly doubt they get much traffic, and it would be all from us, right? I'd say just live with it, especially if we can enable [pseudo-unique visitor counting](https://www.goatcounter.com/help/visitor-counter).

**Comment by maximlt** [comment]
> and it would be all from us, right?

I know at some points users found Panel's dev site on Google. I just tried and didn't, so maybe we've done something to fix that. Agree it's not so important in the end.
